config/routes.rb
Ror::Application.routes.draw do
  
  get "sessions/new"

  get "users/new"

  resources :articles
  resources :products
  resources :comments

  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#new"
  resources :users

  get "log_in" => "sessions#new", :as => "log_in"  
  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"
  match 'comment/destroy/:id/:article_id' => 'comments#destroy', :as => :delete_comment

  namespace :admin do
   resources :articles
   resources :products
  end

  root :to => 'welcome#index'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  scope :rating_is_or_above, lambda {|rating| where("rating = ?", rating)}
  
  validates :title,  :uniqueness => true, :presence => true                  
  
  validate :valid_title
  def valid_title
    self.errors[:title] << "can't be filled with by 'nil', 'empty' , and 'blank'" if (title == "nil" || title == "blank" || title == "empty")
  end

  def self.hundred_char
    self.where("LENGTH(body) > 100")
  end
  
  def search_article 
     Article.where("title ilike ?", "%my country%")
  end  
  
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
	before_filter :require_admin_login

  def index
    @articles = Article.all
    @user = User.all
  end

	def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comments = @article.comments
  end

  def new
    @article = Article.new  
  end

  def create
    @article= Article.new(params[:article].merge({:user_id => current_user.id, :rating => 1}))
    if @article.save
      flash[:notice] = "Article successfully saved"
      redirect_to admin_articles_path
    else
      flash.now[:notice] = "Article failed to saved"
      render :action => :new
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      redirect_to admin_articles_path, :notice => 'Article was successfully updated.'
    else
      flash[:error] = 'Article was failed to update.'
      render :action => 'edit'
    end
  end

  def destroy
    if Article.destroy(params[:id])
      redirect_to admin_articles_path, :notice => 'Article was successfully deleted'
    else
      redirect_to admin_articles_path, :notice => 'you cant delete'
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_login, :only => [:new, :create, :edit, :update, :destroy]
  
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comments = @article.comments
  end

  def new
    @article = Article.new  
  end

  def create
    @article= Article.new(params[:article].merge({:user_id => current_user.id, :rating => 1}))
    if @article.save
      flash[:notice] = "Article successfully saved"
      redirect_to :action => :index
    else
      flash.now[:notice] = "Article failed to saved"
      render :action => :new
    end
  end
  
  def edit
    if Article.find(params[:id]).user_id == current_user.id
      @article = Article.find(params[:id])
    else
      redirect_to articles_path, :notice => 'you cant edit'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      redirect_to articles_path, :notice => 'Article was successfully updated.'
    else
      flash[:error] = 'Article was failed to update.'
      render :action => 'edit'
    end
  end

  def index
    @articles = Article.all
    @user = User.all
    @article_hundred_char = Article.hundred_char
  end

  def destroy
    if Article.find(params[:id]).user_id == current_user.id
      Article.destroy(params[:id])
      redirect_to articles_path, :notice => 'Article was successfully deleted'
    else
      redirect_to articles_path, :notice => 'you cant delete'
    end
  end

end

app/views/admin/articles/edit.html.erb
<h1>Edit Article</h1>
<table>
<%= form_for [:admin, @article] do |article| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <tr>
    <td><%= article.label :title %></td>
    <td><%= article.text_field :title %></td>
  </tr>
  <tr>
    <td><%= article.label :body %></td>
    <td><%= article.text_area :body %></td>
  </tr>
  <tr>
    <td><%= article.submit %></td>
  </tr>
<% end %>
</table>

app/views/admin/articles/index.html.erb
<%= flash[:notice] %>
<h1>List Of Articles</h1>
<table class=list_articles>
  <tr>
    <td>Title</td>
    <td>Content</td>
    <td>Option</td>
  </tr>
  <% @articles.each do |article|%>
  <tr>
  <td><%= article.title %></td>
  <td><%= article.body %>
  <td><%= link_to "Show", admin_article_path(article), :class => "no-border" %> 
    <% if current_user.present? %>
    <%= link_to 'Edit', edit_admin_article_path(article) %> 
    <%= link_to 'Delete', admin_article_path(article.id), :confirm => 'Are you sure want to delete this item?', :method => :delete %>
    <% end %>
  </tr>
  <% end %>
</table>
<p><%= link_to "Add new Article", new_admin_article_path%></p>

app/views/admin/articles/new.html.erb
<h1>New Article</h1>
<%= flash[:notice] %>
<table>
<%= form_for [:admin, @article] do |article| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <tr>
    <td><%= article.label :title %></td>
    <td><%= article.text_field :title %></td>
  </tr>
  <tr>
    <td><%= article.label :body %></td>
    <td><%= article.text_area :body %></td>
  </tr>
  <tr>
    <td><%= article.submit %></td>
  </tr>
<% end %>
</table>

app/views/admin/articles/show.html.erb
 <div class="content">
  <div class="hr_two"></div>
  <h4><%= @article.title %></h4>
  <div class="hr_two"></div>
  <section>
    <article>
      <%= @article.body %>
    </article>
    <article id="list_comments">
      <%= render :partial => "comments/list_comments", :locals => {:comments => @comments, :article => @article}  %>
    </article>
    <% unless session[:user_id].nil? %>
      <article id="comment">
        <%= form_for @comment, :remote => true do |f| %>
          <%= f.hidden_field "user_id", :value => current_user.id %>
          <%= f.hidden_field "article_id", :value => @article.id %>
          <%= f.label :comment %> : <br />
          <%= f.text_area :comment, :cols => 30, :rows => 4 %><br />
          <%= f.submit "Comment" %>
        <% end %>
      </article>
    <% end %>
    <br />
    <%= link_to "Back", admin_articles_path %>
  </section>
</div>