config/routes.rb
Ror::Application.routes.draw do
  
  get "sessions/new"

  get "users/new"

  resources :articles
  resources :products
  resources :comments

  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#new"
  resources :users

  get "log_in" => "sessions#new", :as => "log_in"  
  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"
  match 'comment/destroy/:id/:article_id' => 'comments#destroy', :as => :delete_comment

  namespace :admin do
   resources :articles
   resources :products
  end

  root :to => 'welcome#index'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :categories, :through => :categories_products
  has_many :categories_products
  
  scope :price_more_than_1000, where("price > 1000")
  scope :containing_red, where("description like '%red%'")
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::ApplicationController
  before_filter :require_admin_login

  def index
    @products = Product.all
    @product = Product.price_more_than_1000
    @red = Product.containing_red
  end

  def new
    @product = Product.new
    @categories = Category.all.map{|x| [x.name, x.id]}
  end

  def create
    @product = User.first.products.new(params[:product])
    @categories = Category.all.map{|x| [x.name, x.id]}
    if @product.save
      flash[:notice] = "Your product has been created"
      redirect_to admin_products_path
    else
      flash[:error] = "Your product failed to create"
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :require_login,:only => [:new, :create]
  def index
    @products = Product.all
    @product = Product.price_more_than_1000
    @red = Product.containing_red
  end

  def new
    @product = Product.new
    @categories = Category.all.map{|x| [x.name, x.id]}
  end

  def create
    @product = User.first.products.new(params[:product])
    @categories = Category.all.map{|x| [x.name, x.id]}
    if @product.save
      flash[:notice] = "Your product has been created"
      redirect_to products_path
    else
      flash[:error] = "Your product failed to create"
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end
  
end

app/views/admin/products/index.html.erb
<div class="content">
  <div class="hr_two"></div>
  <h4>Listing Products</h4>
  <div class="hr_two"></div>
  <div class="products">
    <% @products.each do |product| %>
      <div class="product">
        <p>
          Name : <%= product.name %><br />
          Price : <%= product.price %>
          <ul>
            <li><%= link_to "detail", admin_product_path(product) %></li>
          </ul>
        </p>
      </div>
    <% end %>
    <h4>Listing Products Price more than 1000 </h4>
    <% @product.each do |f| %>
      <div class="product">
        <p>
          Name : <%= f.name %><br />
          Price : <%= f.price %>
          <ul>
            <li><%= link_to "detail", admin_product_path(f) %></li>
          </ul>
        </p>
      </div>
    <% end %>
    
    <h4>Listing Products containing red </h4>
    <% @red.each do |r| %>
      <div class="product">
        <p>
          Name : <%= r.name %><br />
          Price : <%= r.price %>
          <ul>
            <li><%= link_to "detail", admin_product_path(r) %></li>
          </ul>
        </p>
      </div>
    <% end %>
    
    <li><%= link_to "add product", new_admin_product_path %></li>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="content">
  <div class="hr_two"></div>
  <h4>New Product</h4>
  <div class="hr_two"></div>
  <%= form_for [:admin, @product] do |f| %>
    <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
        <ul>
          <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <table>
      <tbody>
        <tr>
          <td><%= f.label :name %></td>
          <td>:</td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td><%= f.label :description %></td>
          <td>:</td>
          <td><%= f.text_area :description, :cols => 35, :rows => 5 %></td>
        </tr>
        <tr>
          <td><%= f.label :price %></td>
          <td>:</td>
          <td><%= f.text_field :price %></td>
        </tr>
        <tr>
            <td><%= f.label :category %></td>
            <td>:</td>
            <td><%= f.select :category_id, @categories, { :include_blank => true } %></td>
        </tr>        
      </tbody>
    </table>
    <%= f.submit "Create" %><br /><br />
    <%= link_to "Back", admin_products_path %>
  <% end %>
</div>

app/views/admin/products/show.html.erb
<h4><%= @product.name %></h4> 
  <p>
    <strong>Description :</strong><br />
    <%= @product.description %>
  </p>
  <p>
    <strong>Price :</strong><br />
    <%= @product.price %>
  </p>
<%= link_to "Back", admin_products_path %>
  